[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"

[window]
decorations = "None"
startup_mode = "Maximized"
dynamic_padding = false
padding = { x = 0, y = 0 }

# Font section
[font]
size = 11

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[font.bold]
style = "Regular"

# Color section
[colors]
draw_bold_text_with_bright_colors = false

[general]
import = [
    "themes/material_design.toml"
]
