#!/bin/sh
alias ls='ls --color=auto'
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias sgrep='grep -R -n -H -C 5 --exclude-dir={.git,.svn,CVS} '
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

if type lsd > /dev/null; then
    alias ls='lsd'
    alias l='lsd -l'
    alias ll='lsd -l'
    alias la='lsd -la'
    alias tree='lsd --tree'
elif type exa > /dev/null; then
    alias ls='exa'
    alias l='exa -l'
    alias ll='exa -l'
    alias la='exa -la'
    alias tree='exa --tree'
else
    # ls, the common ones I use a lot shortened for rapid fire usage
    alias l='ls -lFh'     #size,show type,human readable
    alias la='ls -lAFh'   #long list,show almost all,show type,human readable
    alias lr='ls -tRFh'   #sorted by date,recursive,show type,human readable
    alias lt='ls -ltFh'   #long list,sorted by date,show type,human readable
    alias ll='ls -l'      #long list
    alias ldot='ls -ld .*'
    alias lS='ls -1FSsh'
    alias lart='ls -1Fcart'
    alias lrt='ls -1Fcrt'
fi

alias zshrc='${=EDITOR} ${ZDOTDIR:-$HOME}/.zshrc' # Quick access to the .zshrc file

alias t='tail -f'

# easier to read disk
if type duf > /dev/null; then
    alias df='duf'              # Better file disk usage
else
    alias df='df -Hl'           # human-readable sizes
fi

if type free > /dev/null; then
    alias free='free -m'                      # show sizes in MB
fi

# get top process eating memory
alias psmem='ps aux | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps aux | sort -nr -k 3 | head -5'

# Use dark color for ncdu
if type ncdu > /dev/null; then
    alias ncdu='ncdu --color=dark'
fi

# git aliases
zsh_add_file "aliases/git.zsh"

