#!/bin/sh
HISTFILE="$HOME"/.local/share/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH

# Golang setup
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
