# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
export EDITOR='nvim'

# Golang setup
export GOPATH=$HOME/.go

# export PAGER="most"

export PATH

