vim.loader.enable()

require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.autocommands"
require "user.bufferline"
require "user.colorscheme"
require "user.comment"
require "user.gitsigns"
require "user.indentline"
require "user.lsp"
require "user.lualine"
require "user.nvim-tree"
require "user.project"
require "user.telescope"
require "user.toggleterm"
require "user.treesitter"
require "user.whichkey"
